# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_question_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='oid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Option'),
            preserve_default=False,
        ),
    ]
