# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171208_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option',
        ),
    ]
